/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.TaiKhoan;
import Service.SendMail;
import Service.TaiKhoanDao;
import java.awt.Color;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QuenMK_View extends javax.swing.JFrame {

    /**
     * Creates new form QuenMK_View
     */
    TaiKhoanDao service = new TaiKhoanDao();
    SendMail sendMail = new SendMail();
    String code;

    public QuenMK_View() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_maOTP = new javax.swing.JTextField();
        btn_getMa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_ThongBaoTimeOTP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quên Mật Khẩu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(405, 422));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("QUÊN MẬT KHẨU");

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Email.setText("Email");

        txt_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_EmailMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nhập OTP");

        txt_maOTP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_maOTP.setEnabled(false);

        btn_getMa.setBackground(new java.awt.Color(255, 153, 51));
        btn_getMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_getMa.setForeground(new java.awt.Color(255, 255, 255));
        btn_getMa.setText("Lấy Mã");
        btn_getMa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btn_getMa.setBorderPainted(false);
        btn_getMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getMaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EXIT");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Đổi Mật Khẩu");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbl_ThongBaoTimeOTP.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Email)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_maOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_getMa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_ThongBaoTimeOTP))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getMa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ThongBaoTimeOTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_getMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getMaActionPerformed
        // lấy mã 
        this.clickHover();
    }//GEN-LAST:event_btn_getMaActionPerformed

    private void txt_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_EmailMouseClicked
        // reset error 
        this.resetError();
    }//GEN-LAST:event_txt_EmailMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // nút đổi mật khẩu 
        this.doiMatKhau();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMK_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMK_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMK_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMK_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMK_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_getMa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_ThongBaoTimeOTP;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_maOTP;
    // End of variables declaration//GEN-END:variables

    private void clickHover() {
        // Nhập email 
        if (txt_Email.getText().isBlank()) {
            txt_Email.setBackground(Color.red);
            lbl_Email.setText("Vui lòng nhập email");
            lbl_Email.setForeground(Color.red);
        } else {
            this.checkAccount();
        }
    }

    private void labelGuiOTP() {
        btn_getMa.setBackground(Color.red);
        btn_getMa.setEnabled(false);
        txt_maOTP.setEnabled(true);
        txt_maOTP.setText("");
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 30; i >= 0; i--) {
                    try {
                        Thread.sleep(1000);
                        lbl_ThongBaoTimeOTP.setText("Nhận mã mới sau " + String.valueOf(i));
                        if (i == 0) {
                            btn_getMa.setEnabled(true);
                            lbl_ThongBaoTimeOTP.setText("");
                            btn_getMa.setBackground(Color.ORANGE);
                            code = randum();
                            sendMail.send(txt_Email.getText(), code);
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(QuenMK_View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    // Xóa thông báo lỗi 
    private void resetError() {
        txt_Email.setBackground(Color.WHITE);
        lbl_Email.setText("Email");
        lbl_Email.setForeground(Color.BLACK);
    }

    // check vadidate trống thông tin 
    boolean checkTrongTT() {
        if (txt_Email.getText().isBlank() || txt_maOTP.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin ");
            return false;
        } else {
            return true;
        }
    }

    // Vadidate trống thông tin email 
    boolean checkTrongTTemail() {
        if (txt_Email.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email ");
            return false;
        } else {
            return true;
        }
    }

    // Check email có tồn tại trên hệ thông hoặc đã khóa 
    private void checkAccount() {
        if (checkTrongTTemail() == true) {
            String email = txt_Email.getText().trim();
            int check = 0;
            for (TaiKhoan x : service.getTaiKhoanNV()) {
                // Đăng nhập thành công 
                if (email.equalsIgnoreCase(x.getEmail())) {
                    // Check trạng thái tài khoản 
                    for (TaiKhoan tt : service.getChucVu(email)) {
                        // Tài khoản không hoạt động 
                        if (tt.getTrangThaiNV() == 0) {
                            JOptionPane.showMessageDialog(this, "Tài khoản không còn hoạt dộng");
                        } // Tài khoản còn hoạt động
                        else {
                            // Gửi thông báo TOP 
                            this.labelGuiOTP();
                        }
                    }
                    check = 1;
                }
            }
            // đăng nhập thất bại 
            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại trên hệ thống !");
            }
        }
    }

    // Tạo số ngẫu nhiên 
    public String randum() {
        Random rd = new Random();
        int numberCode = rd.nextInt(1000) + 1000;
        return String.valueOf(numberCode);
    }

    // Check OTP 
    boolean checkOTP() {
        if (txt_maOTP.getText().trim().equalsIgnoreCase(code)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR : Mã OTP Không chính xác \n Vui Lòng Kiểm Tra Và Nhập Lại Mã OTP ");
            return false;
        }
    }

    // Nhập đúng thông tin 
    void doiMatKhau() {
        if (checkTrongTT() == true) {
            if (checkOTP() == true) {
                DoiMK_View dmk = new DoiMK_View(txt_Email.getText());
                dmk.setVisible(true);
                this.dispose();
            }
        }
    }
}
